import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, extname, resolve } from "node:path";

const processedDir = resolve("sde/processed");
const outputDir = resolve("src/lib/sde/generated");
const interfaces = new Map<string, { records: JsonObject[]; name: string }>();

type JsonValue = null | boolean | number | string | JsonValue[] | JsonObject;
type JsonObject = { [key: string]: JsonValue | undefined };

function typeName(value: string) {
  const name = value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .replace(/(^|\s)(\w)/g, (_, _space, letter) => letter.toUpperCase());
  return /^[A-Za-z]/.test(name) ? name : `Sde${name}`;
}

function propertyName(value: string) {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) return value;
  const name = value.replace(/[^a-zA-Z0-9]+(.)/g, (_, letter) => String(letter).toUpperCase());
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(value);
}

function primitiveType(values: JsonValue[]) {
  const types = new Set(
    values.map((value) =>
      value === null ? "null" : Array.isArray(value) ? "array" : typeof value,
    ),
  );
  if (types.has("array") || types.has("object")) return "unknown";
  return (
    [...types].map((value) => (value === "number" ? "number" : value)).join(" | ") || "unknown"
  );
}

function inferType(values: JsonValue[], name: string): string {
  const nonNull = values.filter((value) => value !== null);
  if (nonNull.length === 0) return "null";
  if (nonNull.every(Array.isArray)) {
    const elements = nonNull.flatMap((value) => value as JsonValue[]);
    return elements.length === 0 ? "unknown[]" : `${inferType(elements, `${name}Item`)}[]`;
  }
  if (nonNull.every((value) => typeof value === "object" && !Array.isArray(value))) {
    const records = nonNull as JsonObject[];
    addInterface(name, records);
    return name;
  }
  return primitiveType(values);
}

function addInterface(name: string, records: JsonObject[]) {
  const existing = interfaces.get(name);
  if (existing) {
    existing.records.push(...records);
    return;
  }
  interfaces.set(name, { name, records: [...records] });
}

function renderInterface(definition: { name: string; records: JsonObject[] }) {
  const keys = [...new Set(definition.records.flatMap((record) => Object.keys(record)))].sort();
  const lines = keys.map((key) => {
    const values = definition.records
      .map((record) => record[key])
      .filter((value): value is JsonValue => value !== undefined);
    const optional = values.length < definition.records.length ? "?" : "";
    return `  ${propertyName(key)}${optional}: ${inferType(values, `${definition.name}${typeName(key)}`)};`;
  });
  return `export interface ${definition.name} {\n${lines.join("\n")}\n}`;
}

async function main() {
  const files = (await readdir(processedDir)).filter((file) => extname(file) === ".json").sort();
  if (files.length === 0) {
    throw new Error("No processed SDE JSON files found. Run npm run parse-sde first.");
  }

  const datasets: string[] = [];
  for (const file of files) {
    const datasetName = typeName(basename(file, ".json"));
    const value = JSON.parse(await readFile(resolve(processedDir, file), "utf8")) as JsonValue;
    const records = Array.isArray(value)
      ? value.filter(
          (item): item is JsonObject => !!item && typeof item === "object" && !Array.isArray(item),
        )
      : [];
    if (records.length === 0) continue;
    addInterface(`${datasetName}Record`, records);
    datasets.push(datasetName);
  }

  const renderedInterfaces: string[] = [];
  const pendingInterfaces = [...interfaces.keys()];
  for (let index = 0; index < pendingInterfaces.length; index += 1) {
    const name = pendingInterfaces[index];
    const definition = interfaces.get(name);
    if (!definition) continue;
    renderedInterfaces.push(renderInterface(definition));
    for (const discoveredName of interfaces.keys()) {
      if (!pendingInterfaces.includes(discoveredName)) pendingInterfaces.push(discoveredName);
    }
  }

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(outputDir, { recursive: true });
  await writeFile(
    resolve(outputDir, "shared.ts"),
    [
      "// Generated by scripts/generate-types.ts. Do not edit.",
      "export type SdeScalar = string | number | boolean | null;",
      "",
    ].join("\n"),
  );

  const tableFiles: string[] = [];
  for (const datasetName of datasets) {
    const rootName = `${datasetName}Record`;
    const tableInterfaces = renderedInterfaces.filter(
      (definition) =>
        definition.startsWith(`export interface ${rootName}`)
        || definition.includes(` ${rootName}`),
    );
    const tableOutput = [
      "// Generated by scripts/generate-types.ts. Do not edit.",
      ...tableInterfaces,
      `export type ${datasetName} = ${rootName}[];`,
      "",
    ].join("\n\n");
    const fileName = `${basename(datasetName)
      .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
      .replace(/^-/, "")}.ts`;
    await writeFile(resolve(outputDir, fileName), tableOutput);
    tableFiles.push(fileName.replace(/\.ts$/, ""));
  }

  const indexOutput = [
    "// Generated by scripts/generate-types.ts. Do not edit.",
    'export * from "./shared";',
    ...tableFiles.map((file) => `export * from \"./${file}\";`),
    `export const processedSdeFiles = ${JSON.stringify(datasets)} as const;`,
    "",
  ].join("\n");
  await writeFile(resolve(outputDir, "index.ts"), indexOutput);
  console.log(
    `Generated ${interfaces.size} interfaces across ${datasets.length} SDE table files in ${outputDir}`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
